version: 2

models:
  - name: stg_jobs
    columns:
      - name: link
        tests:
          - not_null
      - name: job_title
        tests:
          - not_null
      - name: seniority_label
        tests:
          - accepted_values:
              values: ['Junior', 'Not Specified']
      - name: is_remote

  - name: fct_job_leads
    description: "The final de-duplicated list of jobs."
    columns:
      - name: link
        tests:
          - unique
          - not_null